### ISSUE TITLE
I don't see test.py

### ISSUE THREAD

**Issue by hisplan** [jamesksh0130/bcd-test#1]
You're supposed to add `test.py` to this repo, but I don't see it.

**Comment by jamesksh0130** [comment]
I just added test.py to the repo.
Thanks for your advice.

2024년 4월 8일 (월) 오후 7:17, Jaeyoung Chun ***@***.***>님이 작성:

**Comment by jamesksh0130** [comment]
I just found how to add test.py to the repo and did it.

**Comment by hisplan** [comment]
Alright. Issue resolved! Let's move on to the next one.
